/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'acath' at '6/5/14 10:31 AM' with Gradle 1.11
 *
 * @author acath, @date 6/5/14 10:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
